"""Blind v5 Family: Variable Choice (30 pairs, 60 cases).

Choice count distribution:
- K=8: 15 pairs (var_01 to var_15)
- K=12: 5 pairs (var_16 to var_20)
- K=16: 10 pairs (var_21 to var_30)

Zero model inference during authoring; 100% fresh domain scenarios.
Token length strictly controlled (all <= 350 tokens, choice text kept concise).
"""

from __future__ import annotations
from typing import Any, Dict, List


def get_variable_choice_pairs() -> List[Dict[str, Any]]:
    pairs = []

    # K=8: 15 pairs (01..15)
    k8_defs = [
        (
            "01",
            "救命救急センターの病床管理トリアージ転送規程。救急患者の病態に応じ指定病棟（高度救命・ICU・CCU・脳卒中SCU・小児ICU・熱傷HCU・一般外科・観察病床）へ直接搬送する。",
            "傷病者所見：『急性心筋梗塞による心原性ショックを呈し経皮的冠動脈インターベンション（PCI）直後』。転送先病棟を選択せよ。",
            "ward_ccu_cardiac",
            "傷病者所見：『超急性期脳梗塞によりrt-PA静注療法中、血栓回収療法待機』。転送先病棟を選択せよ。",
            "ward_scu_stroke",
            [
                ("ward_er_advanced_life", "高度救命救急病棟"),
                ("ward_icu_general", "総合ICU病室"),
                ("ward_ccu_cardiac", "心疾患CCU集中治療室"),
                ("ward_scu_stroke", "脳卒中SCU病棟"),
                ("ward_picu_pediatric", "小児PICU集中治療室"),
                ("ward_hcu_burn", "重症熱傷HCU病床"),
                ("ward_general_surgery", "一般外科病棟"),
                ("ward_observation_bed", "救急観察病床"),
            ],
        ),
        (
            "02",
            "高密度鉄道運行の信号現示規程。地上信号機は線路前方空き閉塞数に応じ、停止(R)・警戒(YY)・注意(Y)・減速(YG)・進行(G)・高速進行(GG)・誘導(YF)・入換(W)を現示する。",
            "閉塞制御ロジック：前方第1閉塞区間に先行列車が在線中である。直近信号機の現示を選択せよ。",
            "signal_stop_r",
            "閉塞制御ロジック：前方3閉塞区間が連続開通しており、制限速度105km/hでの進入を指示する。現示を選択せよ。",
            "signal_decelerate_yg",
            [
                ("signal_stop_r", "停止現示R"),
                ("signal_warning_yy", "警戒現示YY"),
                ("signal_caution_y", "注意現示Y"),
                ("signal_decelerate_yg", "減速現示YG"),
                ("signal_proceed_g", "進行現示G"),
                ("signal_high_speed_gg", "高速進行現示GG"),
                ("signal_call_on_yf", "誘導現示YF"),
                ("signal_shunting_w", "入換信号W"),
            ],
        ),
        (
            "03",
            "石油化学複合体の原料エチレンガス分配マニホールド規程。需要プラント（1号重合炉・2号重合炉・酸化炉・酢酸エチル塔・塩ビモノマー・合成ゴム・スチレン・余剰貯蔵タンク）へ最適送液する。",
            "需給指示：『高密度ポリエチレン製造のため1号重合炉へ原料供給を集中せよ』。供給先を選択せよ。",
            "feed_poly_reactor_1",
            "需給指示：『自動車用合成ゴム重合プラントへの原料送入を開始せよ』。供給先を選択せよ。",
            "feed_synthetic_rubber",
            [
                ("feed_poly_reactor_1", "1号重合炉供給"),
                ("feed_poly_reactor_2", "2号重合炉供給"),
                ("feed_oxidation_furnace", "エチレン酸化炉供給"),
                ("feed_ethyl_acetate_tower", "酢酸エチル塔供給"),
                ("feed_vinyl_chloride_monomer", "塩化ビニルモノマー供給"),
                ("feed_synthetic_rubber", "合成ゴムプラント供給"),
                ("feed_styrene_monomer", "スチレンモノマー供給"),
                ("feed_buffer_storage_tank", "余剰緩衝貯蔵タンク"),
            ],
        ),
        (
            "04",
            "国際コンテナ港湾の大型コンテナ船着岸バース割当規程。本船喫水・全長・クレーン数に応じ第1〜第8バースへ接岸指示を行う。",
            "入港本船諸元：『全長399m、喫水16.5m、スーパーポストパナマックス型メガコンテナ船』。最深水深岸壁（第1バース）を割り当てよ。",
            "berth_pier_01",
            "入港本船諸元：『全長140m、喫水6.2m、国内フィーダー内航コンテナ船』。小型専用第7バースを割り当てよ。",
            "berth_pier_07",
            [
                ("berth_pier_01", "第1バース深水深岸壁"),
                ("berth_pier_02", "第2バース大型岸壁"),
                ("berth_pier_03", "第3バース一般岸壁"),
                ("berth_pier_04", "第4バース冷蔵岸壁"),
                ("berth_pier_05", "第5バース危険品岸壁"),
                ("berth_pier_06", "第6バース中型岸壁"),
                ("berth_pier_07", "第7バース内航岸壁"),
                ("berth_pier_08", "第8バース修理待機岸壁"),
            ],
        ),
        (
            "05",
            "宇宙探査機ディープスペースネットワーク（DSN）通信局ハンドオーバー規程。探査機の軌道位置と地球自転に応じ地上追尾アンテナ局（臼田・内之浦・ゴールドストーン・マドリード・キャンベラ・マリンディ・クールー・スバールバル）を切り替える。",
            "軌道追尾計算：探査機は北米西海岸対向位置に仰角最大で可視中。アンテナ局を選択せよ。",
            "dsn_goldstone_california",
            "軌道追尾計算：探査機はオーストラリア東部対向位置に仰角最大で可視中。アンテナ局を選択せよ。",
            "dsn_canberra_australia",
            [
                ("dsn_usuda_japan", "臼田宇宙空間観測所"),
                ("dsn_uchinoura_japan", "内之浦宇宙空間観測所"),
                ("dsn_goldstone_california", "ゴールドストーン局"),
                ("dsn_madrid_spain", "マドリード局"),
                ("dsn_canberra_australia", "キャンベラ局"),
                ("dsn_malindi_kenya", "マリンディ局"),
                ("dsn_kourou_french_guiana", "クールー宇宙センター局"),
                ("dsn_svalbard_norway", "スバールバル極域局"),
            ],
        ),
        (
            "06",
            "AIハイパースケールデータセンターのサーバーラック電力配分PDU切替規程。特定クラスタの負荷変動に応じPDU-1〜PDU-8へ高圧DC配電を行う。",
            "クラスタログ：『LLM推論専用クラスタA群の電源ライン切替を実行せよ』。指定主給電ラインPDU-3を選択せよ。",
            "pdu_cluster_line_03",
            "クラスタログ：『高速ストレージCephノード群の電源ライン切替を実行せよ』。指定給電ラインPDU-8を選択せよ。",
            "pdu_cluster_line_08",
            [
                ("pdu_cluster_line_01", "PDU-01配電ライン"),
                ("pdu_cluster_line_02", "PDU-02配電ライン"),
                ("pdu_cluster_line_03", "PDU-03配電ライン"),
                ("pdu_cluster_line_04", "PDU-04配電ライン"),
                ("pdu_cluster_line_05", "PDU-05配電ライン"),
                ("pdu_cluster_line_06", "PDU-06配電ライン"),
                ("pdu_cluster_line_07", "PDU-07配電ライン"),
                ("pdu_cluster_line_08", "PDU-08配電ライン"),
            ],
        ),
        (
            "07",
            "多目的ダムの洪水吐きゲート操作規程。下流河川水位とダム流入量に応じクレストゲート1号〜8号（Gate-A〜Gate-H）の放流順序を決定する。",
            "放流指令：『初期洪水調節として中央部最優先ゲートであるGate-D（4号ゲート）の微開放流を開始せよ』。ゲートを選択せよ。",
            "dam_crest_gate_d",
            "放流指令：『右岸側河床洗掘防止のため右翼端ゲートであるGate-H（8号ゲート）の開放を実行せよ』。ゲートを選択せよ。",
            "dam_crest_gate_h",
            [
                ("dam_crest_gate_a", "クレストGate-A放流"),
                ("dam_crest_gate_b", "クレストGate-B放流"),
                ("dam_crest_gate_c", "クレストGate-C放流"),
                ("dam_crest_gate_d", "クレストGate-D放流"),
                ("dam_crest_gate_e", "クレストGate-E放流"),
                ("dam_crest_gate_f", "クレストGate-F放流"),
                ("dam_crest_gate_g", "クレストGate-G放流"),
                ("dam_crest_gate_h", "クレストGate-H放流"),
            ],
        ),
        (
            "08",
            "スマート農業自律散布ドローンの区画指定規程。大規模水田の土壌水分および生育画像解析結果に基づき第1〜第8区画（Zone-1〜Zone-8）へ局所施肥を行う。",
            "マルチスペクトル解析：『葉緑素指数NDVIが顕著に低下している北東第2区画（Zone-2）へ散布せよ』。区画を選択せよ。",
            "drone_spray_zone_02",
            "マルチスペクトル解析：『いもち病斑の初期発生が確認された南西第6区画（Zone-6）へ防除剤を散布せよ』。区画を選択せよ。",
            "drone_spray_zone_06",
            [
                ("drone_spray_zone_01", "Zone-01区画散布"),
                ("drone_spray_zone_02", "Zone-02区画散布"),
                ("drone_spray_zone_03", "Zone-03区画散布"),
                ("drone_spray_zone_04", "Zone-04区画散布"),
                ("drone_spray_zone_05", "Zone-05区画散布"),
                ("drone_spray_zone_06", "Zone-06区画散布"),
                ("drone_spray_zone_07", "Zone-07区画散布"),
                ("drone_spray_zone_08", "Zone-08区画散布"),
            ],
        ),
        (
            "09",
            "新幹線電車の台車振動監視システム（CMS）チャンネル割当規程。車輪フラット・軸受異常を検出するためCh-1〜Ch-8センサを監視する。",
            "状態監視診断：『1号車前台車左側第1軸受の加速度ピーク値が異常値を示した』。該当するCh-1を選択せよ。",
            "cms_vibration_ch_01",
            "状態監視診断：『2号車後台車右側第4軸受の温度および高周波振動が上昇した』。該当するCh-8を選択せよ。",
            "cms_vibration_ch_08",
            [
                ("cms_vibration_ch_01", "CMS振動センサCh-1"),
                ("cms_vibration_ch_02", "CMS振動センサCh-2"),
                ("cms_vibration_ch_03", "CMS振動センサCh-3"),
                ("cms_vibration_ch_04", "CMS振動センサCh-4"),
                ("cms_vibration_ch_05", "CMS振動センサCh-5"),
                ("cms_vibration_ch_06", "CMS振動センサCh-6"),
                ("cms_vibration_ch_07", "CMS振動センサCh-7"),
                ("cms_vibration_ch_08", "CMS振動センサCh-8"),
            ],
        ),
        (
            "10",
            "半導体先端ロジック工場の高純度薬液集中供給バルブ規程。各ウェーハ洗浄ベイへ供給する薬品ライン（Line-A〜Line-H）を制御する。",
            "プロセス要求：『微細パターン洗浄のため超高純度フッ酸（DHF）供給Line-Cを開通せよ』。ラインを選択せよ。",
            "valve_supply_line_c",
            "プロセス要求：『レジスト剥離後リンスのため超純水（UPW）供給Line-Gを開通せよ』。ラインを選択せよ。",
            "valve_supply_line_g",
            [
                ("valve_supply_line_a", "薬液供給Line-A"),
                ("valve_supply_line_b", "薬液供給Line-B"),
                ("valve_supply_line_c", "薬液供給Line-C"),
                ("valve_supply_line_d", "薬液供給Line-D"),
                ("valve_supply_line_e", "薬液供給Line-E"),
                ("valve_supply_line_f", "薬液供給Line-F"),
                ("valve_supply_line_g", "薬液供給Line-G"),
                ("valve_supply_line_h", "薬液供給Line-H"),
            ],
        ),
        (
            "11",
            "高度浄水処理場の凝集沈殿池系列切替規程。原水濁度変動に応じ第1〜第8沈殿池（Basin-1〜Basin-8）へ薬品混和水を均等分配する。",
            "配管切替要求：『定期点検明けの第4沈殿池（Basin-4）へ混和水の流入を開始せよ』。池を選択せよ。",
            "water_clarifier_basin_04",
            "配管切替要求：『底泥掻寄機補修のため第5沈殿池（Basin-5）への流入を停止せよ』。池を選択せよ。",
            "water_clarifier_basin_05",
            [
                ("water_clarifier_basin_01", "第1凝集沈殿池Basin-1"),
                ("water_clarifier_basin_02", "第2凝集沈殿池Basin-2"),
                ("water_clarifier_basin_03", "第3凝集沈殿池Basin-3"),
                ("water_clarifier_basin_04", "第4凝集沈殿池Basin-4"),
                ("water_clarifier_basin_05", "第5凝集沈殿池Basin-5"),
                ("water_clarifier_basin_06", "第6凝集沈殿池Basin-6"),
                ("water_clarifier_basin_07", "第7凝集沈殿池Basin-7"),
                ("water_clarifier_basin_08", "第8凝集沈殿池Basin-8"),
            ],
        ),
        (
            "12",
            "国際空港の出発搭乗口ゲートアサイン規程。機体サイズと国際線駐機場配置に応じGate-A1〜Gate-A8を割り当てる。",
            "フライト運航計画：『大型ボーイング777-300ER便（搭乗客350名）にGate-A3を割り当てよ』。搭乗口を選択せよ。",
            "airport_gate_a03",
            "フライト運航計画：『近距離国際線エアバスA320便にGate-A6を割り当てよ』。搭乗口を選択せよ。",
            "airport_gate_a06",
            [
                ("airport_gate_a01", "搭乗ゲートGate-A1"),
                ("airport_gate_a02", "搭乗ゲートGate-A2"),
                ("airport_gate_a03", "搭乗ゲートGate-A3"),
                ("airport_gate_a04", "搭乗ゲートGate-A4"),
                ("airport_gate_a05", "搭乗ゲートGate-A5"),
                ("airport_gate_a06", "搭乗ゲートGate-A6"),
                ("airport_gate_a07", "搭乗ゲートGate-A7"),
                ("airport_gate_a08", "搭乗ゲートGate-A8"),
            ],
        ),
        (
            "13",
            "特別高圧変電所の配電フィーダー遮断器（CB）運用規程。工業団地送電線Feeder-1〜Feeder-8の保守入切を行う。",
            "変電保守指図：『半導体受電線Feeder-2の定期点検につきCBを開放遮断せよ』。遮断器を選択せよ。",
            "substation_feeder_cb_02",
            "変電保守指図：『重工業受電線Feeder-7の受電再開につきCBを投入閉路せよ』。遮断器を選択せよ。",
            "substation_feeder_cb_07",
            [
                ("substation_feeder_cb_01", "配電遮断器Feeder-01"),
                ("substation_feeder_cb_02", "配電遮断器Feeder-02"),
                ("substation_feeder_cb_03", "配電遮断器Feeder-03"),
                ("substation_feeder_cb_04", "配電遮断器Feeder-04"),
                ("substation_feeder_cb_05", "配電遮断器Feeder-05"),
                ("substation_feeder_cb_06", "配電遮断器Feeder-06"),
                ("substation_feeder_cb_07", "配電遮断器Feeder-07"),
                ("substation_feeder_cb_08", "配電遮断器Feeder-08"),
            ],
        ),
        (
            "14",
            "大学病院内自動搬送ロボット（AGV）の薬品配送ステーション規程。配送先（Station-1〜Station-8）へ薬剤コンテナを自動搬送する。",
            "調剤ロボット指示：『緊急処置室Station-1へ抗毒素血清を速達搬送せよ』。目的地を選択せよ。",
            "hospital_agv_station_01",
            "調剤ロボット指示：『外来点滴室Station-5へ抗がん剤混注ボトルを搬送せよ』。目的地を選択せよ。",
            "hospital_agv_station_05",
            [
                ("hospital_agv_station_01", "緊急処置室Station-1"),
                ("hospital_agv_station_02", "手術室前Station-2"),
                ("hospital_agv_station_03", "集中治療Station-3"),
                ("hospital_agv_station_04", "無菌調剤Station-4"),
                ("hospital_agv_station_05", "外来点滴Station-5"),
                ("hospital_agv_station_06", "中央検査Station-6"),
                ("hospital_agv_station_07", "小児病棟Station-7"),
                ("hospital_agv_station_08", "放射線科Station-8"),
            ],
        ),
        (
            "15",
            "大型外航船のエンジンテレグラフ（速力伝令器）操船規程。船橋から機関室へ主機回転指示（微速前進・半速前進・全速前進・微速後進・半速後進・全速後進・機関停止・非常全速前進）を下令する。",
            "狭水道通航：『水先人の指示により全速前進（Full Ahead）へ増速せよ』。テレグラフを選択せよ。",
            "telegraph_full_ahead",
            "離岸操船：『係船索レッコー、後方離反のため微速後進（Dead Slow Astern）を発令せよ』。テレグラフを選択せよ。",
            "telegraph_dead_slow_astern",
            [
                ("telegraph_dead_slow_ahead", "微速前進DeadSlowAhead"),
                ("telegraph_half_ahead", "半速前進HalfAhead"),
                ("telegraph_full_ahead", "全速前進FullAhead"),
                ("telegraph_dead_slow_astern", "微速後進DeadSlowAstern"),
                ("telegraph_half_astern", "半速後進HalfAstern"),
                ("telegraph_full_astern", "全速後進FullAstern"),
                ("telegraph_stop_engine", "機関停止StopEngine"),
                ("telegraph_emergency_full_ahead", "非常全速EmergencyFullAhead"),
            ],
        ),
    ]

    for pid, ctx, q1, t1, q2, t2, chs in k8_defs:
        choices = [{"id": cid, "text": ctxt} for cid, ctxt in chs]
        pairs.append({
            "pair_id": f"rc3_blind5_var_{pid}",
            "family": "variable_choice",
            "k": 8,
            "case_1": {
                "id": f"rc3_blind5_var_{pid}_s1",
                "group_id": f"rc3_blind5_var_{pid}",
                "family": "variable_choice",
                "context": ctx,
                "question": q1,
                "choices": choices,
                "target": {"choice_id": t1},
            },
            "case_2": {
                "id": f"rc3_blind5_var_{pid}_s2",
                "group_id": f"rc3_blind5_var_{pid}",
                "family": "variable_choice",
                "context": ctx,
                "question": q2,
                "choices": choices,
                "target": {"choice_id": t2},
            },
        })

    # K=12: 5 pairs (16..20)
    k12_defs = [
        (
            "16",
            "大型船舶用12気筒2ストローク低速ディーゼルエンジンの排気温度モニタリング規程。シリンダー#01〜#12の排気弁異常を特定する。",
            "熱電対計測：『#03シリンダーの排気弁出口温度が設定上限520℃を超過した』。異常気筒を選択せよ。",
            "cyl_exhaust_temp_03",
            "熱電対計測：『#11シリンダーの燃料噴射不良により排気温度が280℃へ急低下した』。異常気筒を選択せよ。",
            "cyl_exhaust_temp_11",
            [
                ("cyl_exhaust_temp_01", "第01気筒排気"),
                ("cyl_exhaust_temp_02", "第02気筒排気"),
                ("cyl_exhaust_temp_03", "第03気筒排気"),
                ("cyl_exhaust_temp_04", "第04気筒排気"),
                ("cyl_exhaust_temp_05", "第05気筒排気"),
                ("cyl_exhaust_temp_06", "第06気筒排気"),
                ("cyl_exhaust_temp_07", "第07気筒排気"),
                ("cyl_exhaust_temp_08", "第08気筒排気"),
                ("cyl_exhaust_temp_09", "第09気筒排気"),
                ("cyl_exhaust_temp_10", "第10気筒排気"),
                ("cyl_exhaust_temp_11", "第11気筒排気"),
                ("cyl_exhaust_temp_12", "第12気筒排気"),
            ],
        ),
        (
            "17",
            "高層オフィスビルの12ゾーン可変風量（VAV）空調ダンパー制御規程。フロア内Zone-01〜Zone-12の個別給気ダンパー開度を制御する。",
            "ゾーン温度センサ：『南側窓際Zone-04の室温が日射により27.8℃に上昇した』。冷風増量すべきVAVを選択せよ。",
            "vav_hvac_zone_04",
            "ゾーン温度センサ：『北東角役員室Zone-09の室温が20.1℃に過冷却された』。風量を絞るべきVAVを選択せよ。",
            "vav_hvac_zone_09",
            [
                ("vav_hvac_zone_01", "VAV空調Zone-01"),
                ("vav_hvac_zone_02", "VAV空調Zone-02"),
                ("vav_hvac_zone_03", "VAV空調Zone-03"),
                ("vav_hvac_zone_04", "VAV空調Zone-04"),
                ("vav_hvac_zone_05", "VAV空調Zone-05"),
                ("vav_hvac_zone_06", "VAV空調Zone-06"),
                ("vav_hvac_zone_07", "VAV空調Zone-07"),
                ("vav_hvac_zone_08", "VAV空調Zone-08"),
                ("vav_hvac_zone_09", "VAV空調Zone-09"),
                ("vav_hvac_zone_10", "VAV空調Zone-10"),
                ("vav_hvac_zone_11", "VAV空調Zone-11"),
                ("vav_hvac_zone_12", "VAV空調Zone-12"),
            ],
        ),
        (
            "18",
            "臨床検査における標準12誘導心電図（ECG）の局所虚血・梗塞部位同定規程。四肢誘導（I, II, III, aVR, aVL, aVF）および胸部誘導（V1, V2, V3, V4, V5, V6）のST変化を解析する。",
            "心電図波形解析：『前壁中隔梗塞を示唆するV2誘導の著明なST上昇（3mm）を検出』。該当誘導を選択せよ。",
            "ecg_lead_v02",
            "心電図波形解析：『下壁梗塞を反映するaVF誘導の病的好異常Q波およびST上昇を検出』。該当誘導を選択せよ。",
            "ecg_lead_avf",
            [
                ("ecg_lead_i", "第I誘導"),
                ("ecg_lead_ii", "第II誘導"),
                ("ecg_lead_iii", "第III誘導"),
                ("ecg_lead_avr", "aVR誘導"),
                ("ecg_lead_avl", "aVL誘導"),
                ("ecg_lead_avf", "aVF誘導"),
                ("ecg_lead_v01", "V1誘導"),
                ("ecg_lead_v02", "V2誘導"),
                ("ecg_lead_v03", "V3誘導"),
                ("ecg_lead_v04", "V4誘導"),
                ("ecg_lead_v05", "V5誘導"),
                ("ecg_lead_v06", "V6誘導"),
            ],
        ),
        (
            "19",
            "多相永久磁石同期発電機の12相コイル絶縁劣化診断規程。相巻線（Phase-01〜Phase-12）の部分放電パルスを監視する。",
            "オンライン部分放電モニタ：『Phase-05の固定子コイル巻線から800pCの高周波放電を検出』。該当相を選択せよ。",
            "generator_phase_coil_05",
            "オンライン部分放電モニタ：『Phase-12の口出線ブッシング絶縁抵抗が低下傾向を示す』。該当相を選択せよ。",
            "generator_phase_coil_12",
            [
                ("generator_phase_coil_01", "Phase-01相巻線"),
                ("generator_phase_coil_02", "Phase-02相巻線"),
                ("generator_phase_coil_03", "Phase-03相巻線"),
                ("generator_phase_coil_04", "Phase-04相巻線"),
                ("generator_phase_coil_05", "Phase-05相巻線"),
                ("generator_phase_coil_06", "Phase-06相巻線"),
                ("generator_phase_coil_07", "Phase-07相巻線"),
                ("generator_phase_coil_08", "Phase-08相巻線"),
                ("generator_phase_coil_09", "Phase-09相巻線"),
                ("generator_phase_coil_10", "Phase-10相巻線"),
                ("generator_phase_coil_11", "Phase-11相巻線"),
                ("generator_phase_coil_12", "Phase-12相巻線"),
            ],
        ),
        (
            "20",
            "大規模農園の輪作体系における月別主作付け計画規程。年間カレンダー（1月〜12月）に応じ各月の主要管理作業を決定する。",
            "営農作業指示：『春小麦の播種および元肥施用を行う3月の主作業を展開せよ』。該当月を選択せよ。",
            "crop_calendar_month_03",
            "営農作業指示：『主食用大豆の成熟収穫および乾燥調製を行う10月の主作業を展開せよ』。該当月を選択せよ。",
            "crop_calendar_month_10",
            [
                ("crop_calendar_month_01", "01月作付け計画"),
                ("crop_calendar_month_02", "02月作付け計画"),
                ("crop_calendar_month_03", "03月作付け計画"),
                ("crop_calendar_month_04", "04月作付け計画"),
                ("crop_calendar_month_05", "05月作付け計画"),
                ("crop_calendar_month_06", "06月作付け計画"),
                ("crop_calendar_month_07", "07月作付け計画"),
                ("crop_calendar_month_08", "08月作付け計画"),
                ("crop_calendar_month_09", "09月作付け計画"),
                ("crop_calendar_month_10", "10月作付け計画"),
                ("crop_calendar_month_11", "11月作付け計画"),
                ("crop_calendar_month_12", "12月作付け計画"),
            ],
        ),
    ]

    for pid, ctx, q1, t1, q2, t2, chs in k12_defs:
        choices = [{"id": cid, "text": ctxt} for cid, ctxt in chs]
        pairs.append({
            "pair_id": f"rc3_blind5_var_{pid}",
            "family": "variable_choice",
            "k": 12,
            "case_1": {
                "id": f"rc3_blind5_var_{pid}_s1",
                "group_id": f"rc3_blind5_var_{pid}",
                "family": "variable_choice",
                "context": ctx,
                "question": q1,
                "choices": choices,
                "target": {"choice_id": t1},
            },
            "case_2": {
                "id": f"rc3_blind5_var_{pid}_s2",
                "group_id": f"rc3_blind5_var_{pid}",
                "family": "variable_choice",
                "context": ctx,
                "question": q2,
                "choices": choices,
                "target": {"choice_id": t2},
            },
        })

    # K=16: 10 pairs (21..30)
    k16_defs = [
        (
            "21",
            "巨大地震観測網の海底地震計アレイ規程。海溝軸沿いに敷設された観測ノード（Node-01〜Node-16）から初動P波を検知する。",
            "リアルタイム震源解析：『海溝北端の観測ノードNode-02が最大P波初動振幅を検知した』。該当ノードを選択せよ。",
            "seismic_array_node_02",
            "リアルタイム震源解析：『海溝最深部の観測ノードNode-15がスロースリップ微動を検知した』。該当ノードを選択せよ。",
            "seismic_array_node_15",
            [
                ("seismic_array_node_01", "地震観測Node-01"),
                ("seismic_array_node_02", "地震観測Node-02"),
                ("seismic_array_node_03", "地震観測Node-03"),
                ("seismic_array_node_04", "地震観測Node-04"),
                ("seismic_array_node_05", "地震観測Node-05"),
                ("seismic_array_node_06", "地震観測Node-06"),
                ("seismic_array_node_07", "地震観測Node-07"),
                ("seismic_array_node_08", "地震観測Node-08"),
                ("seismic_array_node_09", "地震観測Node-09"),
                ("seismic_array_node_10", "地震観測Node-10"),
                ("seismic_array_node_11", "地震観測Node-11"),
                ("seismic_array_node_12", "地震観測Node-12"),
                ("seismic_array_node_13", "地震観測Node-13"),
                ("seismic_array_node_14", "地震観測Node-14"),
                ("seismic_array_node_15", "地震観測Node-15"),
                ("seismic_array_node_16", "地震観測Node-16"),
            ],
        ),
        (
            "22",
            "フォトニックネットワークの超高速光クロスコネクト（OXC）ポート選択規程。波長多重光信号をPort-01〜Port-16へ無瞬断クロスコネクトする。",
            "光パス設定コマンド：『基幹幹線トラフィックを低損失波長スイッチPort-04へルーティングせよ』。ポートを選択せよ。",
            "oxc_fiber_port_04",
            "光パス設定コマンド：『回線障害迂回のためバックアップ回線Port-14へ光パスを瞬時切り替えよ』。ポートを選択せよ。",
            "oxc_fiber_port_14",
            [
                ("oxc_fiber_port_01", "光OXC-Port-01"),
                ("oxc_fiber_port_02", "光OXC-Port-02"),
                ("oxc_fiber_port_03", "光OXC-Port-03"),
                ("oxc_fiber_port_04", "光OXC-Port-04"),
                ("oxc_fiber_port_05", "光OXC-Port-05"),
                ("oxc_fiber_port_06", "光OXC-Port-06"),
                ("oxc_fiber_port_07", "光OXC-Port-07"),
                ("oxc_fiber_port_08", "光OXC-Port-08"),
                ("oxc_fiber_port_09", "光OXC-Port-09"),
                ("oxc_fiber_port_10", "光OXC-Port-10"),
                ("oxc_fiber_port_11", "光OXC-Port-11"),
                ("oxc_fiber_port_12", "光OXC-Port-12"),
                ("oxc_fiber_port_13", "光OXC-Port-13"),
                ("oxc_fiber_port_14", "光OXC-Port-14"),
                ("oxc_fiber_port_15", "光OXC-Port-15"),
                ("oxc_fiber_port_16", "光OXC-Port-16"),
            ],
        ),
        (
            "23",
            "スマートロジスティクス自動倉庫の16連立体通路（Aisle）ディスパッチ規程。荷捌きクレーンをAisle-01〜Aisle-16へ配車する。",
            "WMSピッキング指示：『飲料ケース大量出庫のためAisle-06へスタッカークレーンを急行させよ』。通路を選択せよ。",
            "wms_warehouse_aisle_06",
            "WMSピッキング指示：『冷凍水産パレット格納のためAisle-13へクレーンを割り当てよ』。通路を選択せよ。",
            "wms_warehouse_aisle_13",
            [
                ("wms_warehouse_aisle_01", "倉庫Aisle-01"),
                ("wms_warehouse_aisle_02", "倉庫Aisle-02"),
                ("wms_warehouse_aisle_03", "倉庫Aisle-03"),
                ("wms_warehouse_aisle_04", "倉庫Aisle-04"),
                ("wms_warehouse_aisle_05", "倉庫Aisle-05"),
                ("wms_warehouse_aisle_06", "倉庫Aisle-06"),
                ("wms_warehouse_aisle_07", "倉庫Aisle-07"),
                ("wms_warehouse_aisle_08", "倉庫Aisle-08"),
                ("wms_warehouse_aisle_09", "倉庫Aisle-09"),
                ("wms_warehouse_aisle_10", "倉庫Aisle-10"),
                ("wms_warehouse_aisle_11", "倉庫Aisle-11"),
                ("wms_warehouse_aisle_12", "倉庫Aisle-12"),
                ("wms_warehouse_aisle_13", "倉庫Aisle-13"),
                ("wms_warehouse_aisle_14", "倉庫Aisle-14"),
                ("wms_warehouse_aisle_15", "倉庫Aisle-15"),
                ("wms_warehouse_aisle_16", "倉庫Aisle-16"),
            ],
        ),
        (
            "24",
            "EV大容量バッテリーパック（BMS）の16セル直列セルバランシング規程。個別セル（Cell-01〜Cell-16）の端子電圧を監視する。",
            "BMSテレメトリ：『Cell-03の端子電圧が4.22Vに過充電接近したため放電抵抗を接続せよ』。対象セルを選択せよ。",
            "bms_pack_cell_03",
            "BMSテレメトリ：『Cell-16の電圧が3.15Vまで低下したため個別補機チャージを実施せよ』。対象セルを選択せよ。",
            "bms_pack_cell_16",
            [
                ("bms_pack_cell_01", "電池Cell-01"),
                ("bms_pack_cell_02", "電池Cell-02"),
                ("bms_pack_cell_03", "電池Cell-03"),
                ("bms_pack_cell_04", "電池Cell-04"),
                ("bms_pack_cell_05", "電池Cell-05"),
                ("bms_pack_cell_06", "電池Cell-06"),
                ("bms_pack_cell_07", "電池Cell-07"),
                ("bms_pack_cell_08", "電池Cell-08"),
                ("bms_pack_cell_09", "電池Cell-09"),
                ("bms_pack_cell_10", "電池Cell-10"),
                ("bms_pack_cell_11", "電池Cell-11"),
                ("bms_pack_cell_12", "電池Cell-12"),
                ("bms_pack_cell_13", "電池Cell-13"),
                ("bms_pack_cell_14", "電池Cell-14"),
                ("bms_pack_cell_15", "電池Cell-15"),
                ("bms_pack_cell_16", "電池Cell-16"),
            ],
        ),
        (
            "25",
            "超高層ビルの消火用スプリンクラー16セクター配管制御規程。火災感知区画（Sector-01〜Sector-16）の流水検知弁を開放する。",
            "防災SCADA火災報知：『7階中央サーバ室Sector-05の熱感知器が発報した』。開放すべき流水検知弁を選択せよ。",
            "sprinkler_sector_valve_05",
            "防災SCADA火災報知：『地下2階駐車場Sector-11のスプリンクラーヘッドが開放放水した』。該当セクターを選択せよ。",
            "sprinkler_sector_valve_11",
            [
                ("sprinkler_sector_valve_01", "消火Sector-01"),
                ("sprinkler_sector_valve_02", "消火Sector-02"),
                ("sprinkler_sector_valve_03", "消火Sector-03"),
                ("sprinkler_sector_valve_04", "消火Sector-04"),
                ("sprinkler_sector_valve_05", "消火Sector-05"),
                ("sprinkler_sector_valve_06", "消火Sector-06"),
                ("sprinkler_sector_valve_07", "消火Sector-07"),
                ("sprinkler_sector_valve_08", "消火Sector-08"),
                ("sprinkler_sector_valve_09", "消火Sector-09"),
                ("sprinkler_sector_valve_10", "消火Sector-10"),
                ("sprinkler_sector_valve_11", "消火Sector-11"),
                ("sprinkler_sector_valve_12", "消火Sector-12"),
                ("sprinkler_sector_valve_13", "消火Sector-13"),
                ("sprinkler_sector_valve_14", "消火Sector-14"),
                ("sprinkler_sector_valve_15", "消火Sector-15"),
                ("sprinkler_sector_valve_16", "消火Sector-16"),
            ],
        ),
        (
            "26",
            "天体電波干渉計の全天16天区（Sky-Quadrant-01〜Sky-Quadrant-16）指向規程。アンテナアレイの位相中心を目的天区へ指向する。",
            "VLBI観測計画：『銀河系中心ブラックホール探査のためQuadrant-07へ全アンテナを同期指向せよ』。天区を選択せよ。",
            "radio_sky_quadrant_07",
            "VLBI観測計画：『系外高輝度クエーサー較正のためQuadrant-12へアンテナビームを向けよ』。天区を選択せよ。",
            "radio_sky_quadrant_12",
            [
                ("radio_sky_quadrant_01", "天区Quadrant-01"),
                ("radio_sky_quadrant_02", "天区Quadrant-02"),
                ("radio_sky_quadrant_03", "天区Quadrant-03"),
                ("radio_sky_quadrant_04", "天区Quadrant-04"),
                ("radio_sky_quadrant_05", "天区Quadrant-05"),
                ("radio_sky_quadrant_06", "天区Quadrant-06"),
                ("radio_sky_quadrant_07", "天区Quadrant-07"),
                ("radio_sky_quadrant_08", "天区Quadrant-08"),
                ("radio_sky_quadrant_09", "天区Quadrant-09"),
                ("radio_sky_quadrant_10", "天区Quadrant-10"),
                ("radio_sky_quadrant_11", "天区Quadrant-11"),
                ("radio_sky_quadrant_12", "天区Quadrant-12"),
                ("radio_sky_quadrant_13", "天区Quadrant-13"),
                ("radio_sky_quadrant_14", "天区Quadrant-14"),
                ("radio_sky_quadrant_15", "天区Quadrant-15"),
                ("radio_sky_quadrant_16", "天区Quadrant-16"),
            ],
        ),
        (
            "27",
            "航空宇宙部品用5軸マシニングセンタの16本ツールマガジン（Tool-01〜Tool-16）割出規程。加工工程に応じ工具タレットを割り出す。",
            "NC加工プログラム：『チタン合金荒加工のため超硬ラフィングエンドミルTool-01を呼び出せ』。工具を選択せよ。",
            "cnc_magazine_tool_01",
            "NC加工プログラム：『高精度ねじ切り加工のためスレッドミルTool-10をスピンドルへ装填せよ』。工具を選択せよ。",
            "cnc_magazine_tool_10",
            [
                ("cnc_magazine_tool_01", "工具Tool-01"),
                ("cnc_magazine_tool_02", "工具Tool-02"),
                ("cnc_magazine_tool_03", "工具Tool-03"),
                ("cnc_magazine_tool_04", "工具Tool-04"),
                ("cnc_magazine_tool_05", "工具Tool-05"),
                ("cnc_magazine_tool_06", "工具Tool-06"),
                ("cnc_magazine_tool_07", "工具Tool-07"),
                ("cnc_magazine_tool_08", "工具Tool-08"),
                ("cnc_magazine_tool_09", "工具Tool-09"),
                ("cnc_magazine_tool_10", "工具Tool-10"),
                ("cnc_magazine_tool_11", "工具Tool-11"),
                ("cnc_magazine_tool_12", "工具Tool-12"),
                ("cnc_magazine_tool_13", "工具Tool-13"),
                ("cnc_magazine_tool_14", "工具Tool-14"),
                ("cnc_magazine_tool_15", "工具Tool-15"),
                ("cnc_magazine_tool_16", "工具Tool-16"),
            ],
        ),
        (
            "28",
            "広域配電網の16母線（Bus-01〜Bus-16）系統潮流監視規程。過負荷母線を特定し系統分離または母線タイ遮断を行う。",
            "電力潮流SCADA：『工業地域Bus-08の受電有効電力が定格母線容量の105%に達した』。過負荷母線を選択せよ。",
            "grid_substation_bus_08",
            "電力潮流SCADA：『急激な太陽光発電連系増加により住宅地域Bus-14で電圧過上昇を検知』。対象母線を選択せよ。",
            "grid_substation_bus_14",
            [
                ("grid_substation_bus_01", "電力Bus-01"),
                ("grid_substation_bus_02", "電力Bus-02"),
                ("grid_substation_bus_03", "電力Bus-03"),
                ("grid_substation_bus_04", "電力Bus-04"),
                ("grid_substation_bus_05", "電力Bus-05"),
                ("grid_substation_bus_06", "電力Bus-06"),
                ("grid_substation_bus_07", "電力Bus-07"),
                ("grid_substation_bus_08", "電力Bus-08"),
                ("grid_substation_bus_09", "電力Bus-09"),
                ("grid_substation_bus_10", "電力Bus-10"),
                ("grid_substation_bus_11", "電力Bus-11"),
                ("grid_substation_bus_12", "電力Bus-12"),
                ("grid_substation_bus_13", "電力Bus-13"),
                ("grid_substation_bus_14", "電力Bus-14"),
                ("grid_substation_bus_15", "電力Bus-15"),
                ("grid_substation_bus_16", "電力Bus-16"),
            ],
        ),
        (
            "29",
            "超長大橋梁の音響放射（AE）構造健全性評価規程。主塔・ケーブル接合部に配置されたAEセンサ（Sensor-01〜Sensor-16）で破断前兆を検知する。",
            "AE信号アナライザ：『主塔基部Sensor-05から鋼材微小き裂進展に伴う弾性波バーストを検出』。検知センサを選択せよ。",
            "ae_bridge_sensor_05",
            "AE信号アナライザ：『中央吊りワイヤー定着部Sensor-16から素線摩擦破断音を検出』。検知センサを選択せよ。",
            "ae_bridge_sensor_16",
            [
                ("ae_bridge_sensor_01", "AEセンサ-01"),
                ("ae_bridge_sensor_02", "AEセンサ-02"),
                ("ae_bridge_sensor_03", "AEセンサ-03"),
                ("ae_bridge_sensor_04", "AEセンサ-04"),
                ("ae_bridge_sensor_05", "AEセンサ-05"),
                ("ae_bridge_sensor_06", "AEセンサ-06"),
                ("ae_bridge_sensor_07", "AEセンサ-07"),
                ("ae_bridge_sensor_08", "AEセンサ-08"),
                ("ae_bridge_sensor_09", "AEセンサ-09"),
                ("ae_bridge_sensor_10", "AEセンサ-10"),
                ("ae_bridge_sensor_11", "AEセンサ-11"),
                ("ae_bridge_sensor_12", "AEセンサ-12"),
                ("ae_bridge_sensor_13", "AEセンサ-13"),
                ("ae_bridge_sensor_14", "AEセンサ-14"),
                ("ae_bridge_sensor_15", "AEセンサ-15"),
                ("ae_bridge_sensor_16", "AEセンサ-16"),
            ],
        ),
        (
            "30",
            "製薬原薬プラントの16基バルク溶媒貯蔵タンクファーム（Tank-01〜Tank-16）受入規程。ローリー車から指定タンクへ圧送受入を行う。",
            "受入マニホールド指示：『高純度アセトニトリル受入のためTank-02の受入自動弁を開放せよ』。タンクを選択せよ。",
            "pharma_solvent_tank_02",
            "受入マニホールド指示：『脱水エタノール受入のためTank-09の受入自動弁を開放せよ』。タンクを選択せよ。",
            "pharma_solvent_tank_09",
            [
                ("pharma_solvent_tank_01", "貯蔵Tank-01"),
                ("pharma_solvent_tank_02", "貯蔵Tank-02"),
                ("pharma_solvent_tank_03", "貯蔵Tank-03"),
                ("pharma_solvent_tank_04", "貯蔵Tank-04"),
                ("pharma_solvent_tank_05", "貯蔵Tank-05"),
                ("pharma_solvent_tank_06", "貯蔵Tank-06"),
                ("pharma_solvent_tank_07", "貯蔵Tank-07"),
                ("pharma_solvent_tank_08", "貯蔵Tank-08"),
                ("pharma_solvent_tank_09", "貯蔵Tank-09"),
                ("pharma_solvent_tank_10", "貯蔵Tank-10"),
                ("pharma_solvent_tank_11", "貯蔵Tank-11"),
                ("pharma_solvent_tank_12", "貯蔵Tank-12"),
                ("pharma_solvent_tank_13", "貯蔵Tank-13"),
                ("pharma_solvent_tank_14", "貯蔵Tank-14"),
                ("pharma_solvent_tank_15", "貯蔵Tank-15"),
                ("pharma_solvent_tank_16", "貯蔵Tank-16"),
            ],
        ),
    ]

    for pid, ctx, q1, t1, q2, t2, chs in k16_defs:
        choices = [{"id": cid, "text": ctxt} for cid, ctxt in chs]
        pairs.append({
            "pair_id": f"rc3_blind5_var_{pid}",
            "family": "variable_choice",
            "k": 16,
            "case_1": {
                "id": f"rc3_blind5_var_{pid}_s1",
                "group_id": f"rc3_blind5_var_{pid}",
                "family": "variable_choice",
                "context": ctx,
                "question": q1,
                "choices": choices,
                "target": {"choice_id": t1},
            },
            "case_2": {
                "id": f"rc3_blind5_var_{pid}_s2",
                "group_id": f"rc3_blind5_var_{pid}",
                "family": "variable_choice",
                "context": ctx,
                "question": q2,
                "choices": choices,
                "target": {"choice_id": t2},
            },
        })

    return pairs
